# Generated by Django 5.1.3 on 2024-11-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('frute', 'الفواكه'), ('vegetable', 'الخضار'), ('grain', 'الحبوب'), ('herbs', 'الاعشاب'), ('ornamental', 'الزينة')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('water_requirement', models.IntegerField()),
                ('fertilizer_requirement', models.IntegerField()),
                ('harvest', models.IntegerField()),
                ('informations', models.TextField()),
                ('image', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('img1', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('img2', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('img3', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantations.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('planting_date', models.DateField()),
                ('next_watering_date', models.DateField(blank=True, null=True)),
                ('next_fertilization_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('qrowing', 'ينمو'), ('harvested', 'تم الحصاد'), ('failed', 'تالف')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantations.plants')),
            ],
        ),
        migrations.CreateModel(
            name='AreaSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.areas')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantations.seasons')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('area', 'season'), name='unique_area_season')],
            },
        ),
    ]
